[2025-06-20 15:40:01,585] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2025-06-20 15:40:01,585] INFO in _internal: [33mPress CTRL+C to quit[0m
[2025-06-20 15:40:27,646] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2025-06-20 15:40:27,646] INFO in _internal: [33mPress CTRL+C to quit[0m
[2025-06-20 19:53:51,286] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2025-06-20 19:53:51,287] INFO in _internal: [33mPress CTRL+C to quit[0m
[2025-06-20 19:55:57,349] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2025-06-20 19:55:57,349] INFO in _internal: [33mPress CTRL+C to quit[0m
[2025-06-20 19:57:34,422] INFO in _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
[2025-06-20 19:57:34,423] INFO in _internal: [33mPress CTRL+C to quit[0m
[2025-06-20 19:59:34,474] WARNING in routes: Failed login attempt: user1. Validation errors: {}
[2025-06-20 19:59:40,703] INFO in routes: User1 authenticated
[2025-06-20 19:59:42,884] INFO in routes: User1 successfully logged out.
[2025-06-20 20:04:38,543] INFO in routes: User1 authenticated
[2025-06-20 20:04:40,056] INFO in routes: User1 successfully logged out.
[2025-06-20 20:06:29,865] INFO in routes: User1 authenticated
[2025-06-20 20:06:30,765] INFO in routes: User1 successfully logged out.
[2025-06-20 21:35:24,498] INFO in routes: User1 authenticated
[2025-06-20 21:35:24,512] INFO in routes: User1 accessed home page
[2025-06-20 21:35:24,514] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\routes.py", line 153, in index
    tickets=recent_tickets,
            ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'recent_tickets' where it is not associated with a value
[2025-06-20 21:36:27,654] INFO in routes: User1 accessed home page
[2025-06-20 21:36:27,655] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\routes.py", line 154, in index
    tickets=recent_tickets,
            ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'recent_tickets' where it is not associated with a value
[2025-06-20 21:38:19,222] INFO in routes: User1 accessed home page
[2025-06-20 21:38:19,223] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\routes.py", line 154, in index
    tickets=recent_tickets,
            ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'recent_tickets' where it is not associated with a value
[2025-06-20 21:38:51,117] INFO in routes: User1 accessed home page
[2025-06-20 21:38:51,118] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\routes.py", line 154, in index
    tickets=recent_tickets,
            ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'recent_tickets' where it is not associated with a value
[2025-06-20 21:41:15,553] INFO in routes: User1 accessed home page
[2025-06-20 21:41:15,554] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\routes.py", line 156, in index
    tickets=recent_tickets,
            ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'recent_tickets' where it is not associated with a value
[2025-06-20 21:42:05,125] INFO in routes: User1 accessed home page
[2025-06-20 21:42:05,126] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\routes.py", line 152, in index
    tickets=recent_tickets,
            ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'recent_tickets' where it is not associated with a value
[2025-06-20 21:47:23,826] INFO in routes: User1 accessed home page
[2025-06-20 21:47:23,826] ERROR in routes: Error retrieving ticket summary stats: type object 'tickets' has no attribute 'statis'
[2025-06-20 21:50:24,884] INFO in routes: User1 accessed home page
[2025-06-20 21:50:24,884] ERROR in routes: Error retrieving ticket summary stats: type object 'tickets' has no attribute 'statis'
[2025-06-20 21:50:55,229] INFO in routes: User1 accessed home page
[2025-06-20 21:50:55,271] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\routes.py", line 141, in index
    return render_template(
        'index.html',
    ...<3 lines>...
        count_closed=count_closed
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\templates\index.html", line 3, in top-level template code
    {% extends base_template %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\templating.py", line 96, in _get_source_fast
    return loader.get_source(environment, template)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\jinja2\loaders.py", line 197, in get_source
    pieces = split_template_path(template)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\jinja2\loaders.py", line 30, in split_template_path
    for piece in template.split("/"):
                 ^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'base_template' is undefined
[2025-06-20 21:53:33,814] INFO in routes: User1 accessed home page
[2025-06-20 21:53:37,795] INFO in routes: User1 accessed home page
[2025-06-20 22:03:35,035] INFO in routes: User1 accessed home page
[2025-06-20 22:03:37,908] INFO in routes: User1 successfully logged out.
[2025-06-20 22:03:42,344] INFO in routes: User1 authenticated
[2025-06-20 22:03:42,351] INFO in routes: User1 accessed home page
[2025-06-20 22:04:11,376] INFO in routes: User1 accessed home page
[2025-06-20 22:04:43,219] INFO in routes: User1 accessed home page
[2025-06-20 22:05:45,910] INFO in routes: User1 accessed home page
[2025-06-20 22:05:55,567] INFO in routes: User1 accessed home page
[2025-06-20 22:06:00,056] INFO in routes: User1 accessed home page
[2025-06-20 22:06:02,441] INFO in routes: User1 accessed home page
[2025-06-20 22:06:03,755] INFO in routes: User1 accessed home page
[2025-06-20 22:06:04,515] INFO in routes: User1 accessed home page
[2025-06-20 22:06:04,852] INFO in routes: User1 accessed home page
[2025-06-20 22:06:05,013] INFO in routes: User1 accessed home page
[2025-06-20 22:06:05,164] INFO in routes: User1 accessed home page
[2025-06-20 22:06:05,309] INFO in routes: User1 accessed home page
[2025-06-20 22:06:05,441] INFO in routes: User1 accessed home page
[2025-06-20 22:06:05,597] INFO in routes: User1 accessed home page
[2025-06-20 22:06:05,740] INFO in routes: User1 accessed home page
[2025-06-20 22:06:05,893] INFO in routes: User1 accessed home page
[2025-06-20 22:06:06,026] INFO in routes: User1 accessed home page
[2025-06-20 22:06:07,203] INFO in routes: User1 successfully logged out.
[2025-06-20 22:06:11,876] INFO in routes: User1 authenticated
[2025-06-20 22:06:11,883] INFO in routes: User1 accessed home page
[2025-06-20 22:06:41,749] INFO in routes: User1 accessed home page
[2025-06-20 22:08:42,226] INFO in routes: User1 accessed home page
[2025-06-20 22:10:02,637] INFO in routes: User1 accessed home page
[2025-06-20 22:21:06,741] INFO in routes: User1 accessed home page
[2025-06-20 22:21:06,746] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\routes.py", line 117, in index
    count_open=count_open,
               ^^^^^^^^^^
NameError: name 'count_open' is not defined
[2025-06-20 22:21:23,481] INFO in routes: User1 accessed home page
[2025-06-20 22:21:27,693] INFO in routes: User1 successfully logged out.
[2025-06-20 22:22:05,228] ERROR in routes: Error creating new user: 'user_accounts_id' is an invalid keyword argument for login_details
[2025-06-20 22:22:05,228] INFO in routes: New user created: form.username
[2025-06-20 22:24:12,391] ERROR in routes: Error creating new user: 'user_accounts_id' is an invalid keyword argument for login_details
[2025-06-20 22:30:41,209] INFO in routes: User1 authenticated
[2025-06-20 22:30:41,221] INFO in routes: User1 accessed home page
[2025-06-20 22:30:56,753] ERROR in routes: Error creating new ticket: 'user_accounts_id' is an invalid keyword argument for tickets
[2025-06-21 10:30:09,404] INFO in routes: User1 authenticated
[2025-06-21 10:30:09,414] INFO in routes: User1 accessed home page
[2025-06-21 11:05:37,558] INFO in routes: User1 accessed home page
[2025-06-21 11:05:41,355] INFO in routes: User1 view ticket 1
[2025-06-21 11:09:15,235] INFO in routes: User1 view ticket 1
[2025-06-21 11:09:15,269] INFO in routes: Comment added successfully
[2025-06-21 11:09:15,274] INFO in routes: User1 view ticket 1
[2025-06-21 13:47:22,803] INFO in routes: User1 accessed home page
[2025-06-21 13:47:24,739] INFO in routes: User1 successfully logged out.
[2025-06-21 13:47:29,759] INFO in routes: Admin1 authenticated
[2025-06-21 13:47:29,766] INFO in routes: Admin1 accessed home page
[2025-06-21 13:48:15,409] INFO in routes: Admin1 accessed users page.
[2025-06-21 13:48:16,435] INFO in routes: Admin1 accessed closed-tickets page.
[2025-06-21 13:48:16,982] INFO in routes: Admin1 accessed open-tickets page.
[2025-06-21 13:48:17,711] INFO in routes: Admin1 accessed closed-tickets page.
[2025-06-21 13:48:18,188] INFO in routes: Admin1 accessed users page.
[2025-06-21 13:52:33,305] INFO in routes: Admin1 accessed home page
[2025-06-21 13:52:35,838] INFO in routes: Admin1 accessed users page.
[2025-06-21 13:53:43,786] INFO in routes: Admin1 accessed home page
[2025-06-21 13:53:44,790] INFO in routes: Admin1 accessed users page.
[2025-06-21 13:53:47,474] INFO in routes: Admin1 accessed promote user page
[2025-06-21 13:53:47,490] INFO in routes: User1 promoted to admin by Admin1
[2025-06-21 13:53:47,496] INFO in routes: Admin1 accessed users page.
[2025-06-21 14:02:42,439] INFO in routes: Admin1 accessed home page
[2025-06-21 14:02:50,961] INFO in routes: Admin1 accessed users page.
[2025-06-21 14:02:52,902] INFO in routes: User1 demoted to standard user by Admin1
[2025-06-21 14:02:52,910] INFO in routes: Admin1 accessed users page.
[2025-06-21 14:11:27,597] INFO in routes: Admin1 accessed home page
[2025-06-21 14:11:29,781] INFO in routes: Admin1 successfully logged out.
[2025-06-21 14:11:58,397] INFO in routes: New user created: form.username
[2025-06-21 14:12:09,938] WARNING in routes: Failed login attempt: w. Validation errors: {}
[2025-06-21 14:12:21,834] WARNING in routes: Failed login attempt: w. Validation errors: {}
[2025-06-21 14:13:41,854] INFO in routes: New user created: form.username
[2025-06-21 14:13:56,280] WARNING in routes: Failed login attempt: User2. Validation errors: {}
[2025-06-21 14:17:51,777] INFO in routes: New user created: form.username
[2025-06-21 14:18:05,929] INFO in routes: User2 authenticated
[2025-06-21 14:18:05,938] INFO in routes: User2 accessed home page
[2025-06-21 14:18:15,880] INFO in routes: New ticket created successfully 2
[2025-06-21 14:18:15,886] INFO in routes: User2 accessed home page
[2025-06-21 14:18:18,178] INFO in routes: User2 view ticket 2
[2025-06-21 14:18:22,197] INFO in routes: User2 view ticket 2
[2025-06-21 14:18:22,213] INFO in routes: Comment added successfully
[2025-06-21 14:18:22,218] INFO in routes: User2 view ticket 2
[2025-06-21 14:18:29,804] INFO in routes: User2 accessed open-tickets page.
[2025-06-21 14:18:33,745] INFO in routes: User2 accessed closed-tickets page.
[2025-06-21 14:18:37,463] INFO in routes: User2 successfully logged out.
[2025-06-21 14:18:44,054] INFO in routes: Admin1 authenticated
[2025-06-21 14:18:44,060] INFO in routes: Admin1 accessed home page
[2025-06-21 14:18:48,886] INFO in routes: Admin1 view ticket 2
[2025-06-21 14:18:57,471] INFO in routes: Admin1 view ticket 2
[2025-06-21 14:18:57,500] INFO in routes: Comment added successfully
[2025-06-21 14:18:57,505] INFO in routes: Admin1 view ticket 2
[2025-06-21 14:20:56,279] INFO in routes: Admin1 view ticket 2
[2025-06-21 14:20:56,288] INFO in routes: Admin1 accessed home page
[2025-06-21 14:20:59,014] INFO in routes: Admin1 accessed open-tickets page.
[2025-06-21 14:21:01,587] INFO in routes: Admin1 accessed home page
[2025-06-21 14:21:05,535] INFO in routes: New ticket created successfully 3
[2025-06-21 14:21:05,542] INFO in routes: Admin1 accessed home page
[2025-06-21 14:21:06,677] INFO in routes: Admin1 view ticket 3
[2025-06-21 14:21:08,574] INFO in routes: Admin1 view ticket 3
[2025-06-21 14:21:08,585] INFO in routes: Admin1 accessed home page
[2025-06-21 14:21:11,815] INFO in routes: Admin1 accessed users page.
[2025-06-21 14:21:18,323] INFO in routes: Admin1 accessed promote user page
[2025-06-21 14:21:18,341] INFO in routes: User2 promoted to admin by Admin1
[2025-06-21 14:21:18,351] INFO in routes: Admin1 accessed users page.
[2025-06-21 14:21:20,321] INFO in routes: Admin1 successfully logged out.
[2025-06-21 14:21:31,090] INFO in routes: User2 authenticated
[2025-06-21 14:21:31,097] INFO in routes: User2 accessed home page
[2025-06-21 14:21:38,007] INFO in routes: User2 accessed users page.
[2025-06-21 14:21:41,810] INFO in routes: User2 successfully logged out.
[2025-06-21 14:21:47,838] INFO in routes: Admin1 authenticated
[2025-06-21 14:21:47,845] INFO in routes: Admin1 accessed home page
[2025-06-21 14:21:49,632] INFO in routes: Admin1 accessed users page.
[2025-06-21 14:21:54,315] INFO in routes: User2 demoted to standard user by Admin1
[2025-06-21 14:21:54,323] INFO in routes: Admin1 accessed users page.
[2025-06-21 14:21:55,798] INFO in routes: Admin1 successfully logged out.
[2025-06-21 14:22:05,766] INFO in routes: User2 authenticated
[2025-06-21 14:22:05,773] INFO in routes: User2 accessed home page
[2025-06-21 14:22:08,237] INFO in routes: User2 accessed open-tickets page.
[2025-06-21 14:22:08,543] INFO in routes: User2 accessed home page
[2025-06-21 14:22:08,838] INFO in routes: User2 accessed open-tickets page.
[2025-06-21 14:22:09,132] INFO in routes: User2 accessed closed-tickets page.
[2025-06-21 14:22:09,842] INFO in routes: User2 successfully logged out.
[2025-06-21 14:22:20,001] INFO in routes: User2 authenticated
[2025-06-21 14:22:20,007] INFO in routes: User2 accessed home page
[2025-06-21 14:22:21,117] INFO in routes: User2 accessed closed-tickets page.
[2025-06-21 14:23:31,255] INFO in routes: User2 successfully logged out.
[2025-06-21 14:23:42,526] INFO in routes: Admin1 authenticated
[2025-06-21 14:23:42,532] INFO in routes: Admin1 accessed home page
[2025-06-21 14:23:44,175] INFO in routes: Admin1 accessed users page.
[2025-06-21 14:23:49,138] INFO in routes: Admin1 accessed users page.
[2025-06-21 14:23:52,744] INFO in routes: Admin1 successfully logged out.
[2025-06-21 14:24:01,753] WARNING in routes: Failed login attempt: User2. Validation errors: {}
[2025-06-21 21:30:55,912] INFO in routes: User1 authenticated
[2025-06-21 21:30:55,924] INFO in routes: User1 accessed home page
[2025-06-21 21:40:29,173] INFO in routes: testuser authenticated
[2025-06-21 21:40:29,177] INFO in routes: testuser accessed home page
[2025-06-21 21:40:29,270] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 21:40:29,600] INFO in routes: testuser authenticated
[2025-06-21 21:40:29,602] INFO in routes: testuser accessed home page
[2025-06-21 21:40:29,604] INFO in routes: testuser successfully logged out.
[2025-06-21 21:41:27,887] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 21:41:52,602] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 21:42:00,671] INFO in routes: testuser authenticated
[2025-06-21 21:42:00,676] INFO in routes: testuser accessed home page
[2025-06-21 21:42:00,907] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 21:42:01,239] INFO in routes: testuser authenticated
[2025-06-21 21:42:01,241] INFO in routes: testuser accessed home page
[2025-06-21 21:42:01,243] INFO in routes: testuser successfully logged out.
[2025-06-21 21:44:21,860] INFO in routes: testuser authenticated
[2025-06-21 21:44:21,864] INFO in routes: testuser accessed home page
[2025-06-21 21:44:21,956] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 21:44:22,288] INFO in routes: testuser authenticated
[2025-06-21 21:44:22,290] INFO in routes: testuser accessed home page
[2025-06-21 21:44:22,291] INFO in routes: testuser successfully logged out.
[2025-06-21 23:07:05,148] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: user_accounts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
                    ~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\models.py", line 122, in load_user
    return db.session.get(user_accounts, int(id))
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 1058, in get
    return self._proxied.get(
           ~~~~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<6 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3694, in get
    return self._get_impl(
           ~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<7 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3873, in _get_impl
    return db_load_fn(
        self,
    ...<5 lines>...
        bind_arguments=bind_arguments,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
    ~~~~~~~~~~~~~~~^
        q,
        ^^
    ...<2 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user_accounts
[SQL: SELECT user_accounts.user_account_id AS user_accounts_user_account_id, user_accounts.first_name AS user_accounts_first_name, user_accounts.last_name AS user_accounts_last_name, user_accounts.phone_number AS user_accounts_phone_number, user_accounts.account_created_date AS user_accounts_account_created_date, user_accounts.last_login AS user_accounts_last_login, user_accounts.is_deleted AS user_accounts_is_deleted, user_accounts.account_deleted_date AS user_accounts_account_deleted_date, user_accounts.is_admin AS user_accounts_is_admin 
FROM user_accounts 
WHERE user_accounts.user_account_id = ?]
[parameters: (2,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-21 23:17:03,926] INFO in routes: User1 accessed home page
[2025-06-21 23:26:20,125] INFO in routes: testuser authenticated
[2025-06-21 23:26:20,130] INFO in routes: testuser accessed home page
[2025-06-21 23:26:20,227] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:26:20,565] INFO in routes: testuser authenticated
[2025-06-21 23:26:20,567] INFO in routes: testuser accessed home page
[2025-06-21 23:26:20,568] INFO in routes: testuser successfully logged out.
[2025-06-21 23:26:20,910] INFO in routes: testuser authenticated
[2025-06-21 23:26:20,912] INFO in routes: testuser accessed home page
[2025-06-21 23:26:20,914] INFO in routes: testuser accessed home page
[2025-06-21 23:26:21,246] INFO in routes: testuser authenticated
[2025-06-21 23:26:21,248] INFO in routes: testuser accessed home page
[2025-06-21 23:26:21,250] INFO in routes: testuser accessed home page
[2025-06-21 23:28:18,234] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: user_accounts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
                    ~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\models.py", line 122, in load_user
    return db.session.get(user_accounts, int(id))
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 1058, in get
    return self._proxied.get(
           ~~~~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<6 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3694, in get
    return self._get_impl(
           ~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<7 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3873, in _get_impl
    return db_load_fn(
        self,
    ...<5 lines>...
        bind_arguments=bind_arguments,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
    ~~~~~~~~~~~~~~~^
        q,
        ^^
    ...<2 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user_accounts
[SQL: SELECT user_accounts.user_account_id AS user_accounts_user_account_id, user_accounts.first_name AS user_accounts_first_name, user_accounts.last_name AS user_accounts_last_name, user_accounts.phone_number AS user_accounts_phone_number, user_accounts.account_created_date AS user_accounts_account_created_date, user_accounts.last_login AS user_accounts_last_login, user_accounts.is_deleted AS user_accounts_is_deleted, user_accounts.account_deleted_date AS user_accounts_account_deleted_date, user_accounts.is_admin AS user_accounts_is_admin 
FROM user_accounts 
WHERE user_accounts.user_account_id = ?]
[parameters: (2,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-21 23:28:38,608] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: user_accounts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
                    ~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\models.py", line 122, in load_user
    return db.session.get(user_accounts, int(id))
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 1058, in get
    return self._proxied.get(
           ~~~~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<6 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3694, in get
    return self._get_impl(
           ~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<7 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3873, in _get_impl
    return db_load_fn(
        self,
    ...<5 lines>...
        bind_arguments=bind_arguments,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
    ~~~~~~~~~~~~~~~^
        q,
        ^^
    ...<2 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user_accounts
[SQL: SELECT user_accounts.user_account_id AS user_accounts_user_account_id, user_accounts.first_name AS user_accounts_first_name, user_accounts.last_name AS user_accounts_last_name, user_accounts.phone_number AS user_accounts_phone_number, user_accounts.account_created_date AS user_accounts_account_created_date, user_accounts.last_login AS user_accounts_last_login, user_accounts.is_deleted AS user_accounts_is_deleted, user_accounts.account_deleted_date AS user_accounts_account_deleted_date, user_accounts.is_admin AS user_accounts_is_admin 
FROM user_accounts 
WHERE user_accounts.user_account_id = ?]
[parameters: (2,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-21 23:29:26,487] WARNING in routes: Failed login attempt: User1. Validation errors: {}
[2025-06-21 23:30:30,698] INFO in routes: User1 accessed home page
[2025-06-21 23:30:46,632] INFO in routes: testuser authenticated
[2025-06-21 23:30:46,637] INFO in routes: testuser accessed home page
[2025-06-21 23:30:46,722] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:30:47,054] INFO in routes: testuser authenticated
[2025-06-21 23:30:47,056] INFO in routes: testuser accessed home page
[2025-06-21 23:30:47,057] INFO in routes: testuser successfully logged out.
[2025-06-21 23:30:47,399] INFO in routes: testuser authenticated
[2025-06-21 23:30:47,401] INFO in routes: testuser accessed home page
[2025-06-21 23:30:47,402] INFO in routes: testuser accessed home page
[2025-06-21 23:30:47,731] INFO in routes: testuser authenticated
[2025-06-21 23:30:47,733] INFO in routes: testuser accessed home page
[2025-06-21 23:30:47,735] INFO in routes: testuser accessed home page
[2025-06-21 23:32:01,762] INFO in routes: testuser authenticated
[2025-06-21 23:32:01,767] INFO in routes: testuser accessed home page
[2025-06-21 23:32:01,860] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:32:02,200] INFO in routes: testuser authenticated
[2025-06-21 23:32:02,202] INFO in routes: testuser accessed home page
[2025-06-21 23:32:02,203] INFO in routes: testuser successfully logged out.
[2025-06-21 23:32:02,534] INFO in routes: testuser authenticated
[2025-06-21 23:32:02,536] INFO in routes: testuser accessed home page
[2025-06-21 23:32:02,538] INFO in routes: testuser accessed home page
[2025-06-21 23:32:02,866] INFO in routes: testuser authenticated
[2025-06-21 23:32:02,868] INFO in routes: testuser accessed home page
[2025-06-21 23:32:02,870] INFO in routes: testuser accessed home page
[2025-06-21 23:35:37,893] INFO in routes: testuser authenticated
[2025-06-21 23:35:37,898] INFO in routes: testuser accessed home page
[2025-06-21 23:35:37,997] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:35:38,327] INFO in routes: testuser authenticated
[2025-06-21 23:35:38,329] INFO in routes: testuser accessed home page
[2025-06-21 23:35:38,330] INFO in routes: testuser successfully logged out.
[2025-06-21 23:35:38,666] INFO in routes: testuser authenticated
[2025-06-21 23:35:38,668] INFO in routes: testuser accessed home page
[2025-06-21 23:35:38,670] INFO in routes: testuser accessed home page
[2025-06-21 23:35:39,002] INFO in routes: testuser authenticated
[2025-06-21 23:35:39,005] INFO in routes: testuser accessed home page
[2025-06-21 23:35:39,006] INFO in routes: testuser accessed home page
[2025-06-21 23:37:37,364] INFO in routes: testuser authenticated
[2025-06-21 23:37:37,369] INFO in routes: testuser accessed home page
[2025-06-21 23:37:37,451] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:37:37,783] INFO in routes: testuser authenticated
[2025-06-21 23:37:37,786] INFO in routes: testuser accessed home page
[2025-06-21 23:37:37,787] INFO in routes: testuser successfully logged out.
[2025-06-21 23:37:38,129] INFO in routes: testuser authenticated
[2025-06-21 23:37:38,131] INFO in routes: testuser accessed home page
[2025-06-21 23:37:38,133] INFO in routes: testuser accessed home page
[2025-06-21 23:37:38,473] INFO in routes: testuser authenticated
[2025-06-21 23:37:38,475] INFO in routes: testuser accessed home page
[2025-06-21 23:37:38,477] INFO in routes: testuser accessed home page
[2025-06-21 23:38:30,649] INFO in routes: testuser authenticated
[2025-06-21 23:38:30,654] INFO in routes: testuser accessed home page
[2025-06-21 23:38:30,745] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:38:31,086] INFO in routes: testuser authenticated
[2025-06-21 23:38:31,088] INFO in routes: testuser accessed home page
[2025-06-21 23:38:31,089] INFO in routes: testuser successfully logged out.
[2025-06-21 23:38:31,427] INFO in routes: testuser authenticated
[2025-06-21 23:38:31,429] INFO in routes: testuser accessed home page
[2025-06-21 23:38:31,431] INFO in routes: testuser accessed home page
[2025-06-21 23:38:31,756] INFO in routes: testuser authenticated
[2025-06-21 23:38:31,758] INFO in routes: testuser accessed home page
[2025-06-21 23:38:31,759] INFO in routes: testuser accessed home page
[2025-06-21 23:39:52,035] INFO in routes: testuser authenticated
[2025-06-21 23:39:52,039] INFO in routes: testuser accessed home page
[2025-06-21 23:39:52,124] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:39:52,463] INFO in routes: testuser authenticated
[2025-06-21 23:39:52,465] INFO in routes: testuser accessed home page
[2025-06-21 23:39:52,467] INFO in routes: testuser successfully logged out.
[2025-06-21 23:39:52,822] INFO in routes: testuser authenticated
[2025-06-21 23:39:52,825] INFO in routes: testuser accessed home page
[2025-06-21 23:39:52,826] INFO in routes: testuser accessed home page
[2025-06-21 23:39:53,162] INFO in routes: testuser authenticated
[2025-06-21 23:39:53,164] INFO in routes: testuser accessed home page
[2025-06-21 23:39:53,167] INFO in routes: testuser accessed home page
[2025-06-21 23:39:53,167] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-21 23:40:29,879] INFO in routes: testuser authenticated
[2025-06-21 23:40:29,884] INFO in routes: testuser accessed home page
[2025-06-21 23:40:29,968] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:40:30,306] INFO in routes: testuser authenticated
[2025-06-21 23:40:30,308] INFO in routes: testuser accessed home page
[2025-06-21 23:40:30,310] INFO in routes: testuser successfully logged out.
[2025-06-21 23:40:30,652] INFO in routes: testuser authenticated
[2025-06-21 23:40:30,654] INFO in routes: testuser accessed home page
[2025-06-21 23:40:30,655] INFO in routes: testuser accessed home page
[2025-06-21 23:40:30,989] INFO in routes: testuser authenticated
[2025-06-21 23:40:30,991] INFO in routes: testuser accessed home page
[2025-06-21 23:40:30,993] INFO in routes: testuser accessed home page
[2025-06-21 23:40:30,994] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-21 23:40:30,994] INFO in routes: testuser accessed home page
[2025-06-21 23:40:30,994] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-21 23:41:11,201] INFO in routes: testuser authenticated
[2025-06-21 23:41:11,205] INFO in routes: testuser accessed home page
[2025-06-21 23:41:11,292] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:41:11,646] INFO in routes: testuser authenticated
[2025-06-21 23:41:11,648] INFO in routes: testuser accessed home page
[2025-06-21 23:41:11,649] INFO in routes: testuser successfully logged out.
[2025-06-21 23:41:11,989] INFO in routes: testuser authenticated
[2025-06-21 23:41:11,992] INFO in routes: testuser accessed home page
[2025-06-21 23:41:11,994] INFO in routes: testuser accessed home page
[2025-06-21 23:41:12,328] INFO in routes: testuser authenticated
[2025-06-21 23:41:12,330] INFO in routes: testuser accessed home page
[2025-06-21 23:41:12,332] INFO in routes: testuser accessed home page
[2025-06-21 23:41:12,332] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-21 23:41:55,738] INFO in routes: testuser authenticated
[2025-06-21 23:41:55,743] INFO in routes: testuser accessed home page
[2025-06-21 23:41:55,828] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:41:56,162] INFO in routes: testuser authenticated
[2025-06-21 23:41:56,165] INFO in routes: testuser accessed home page
[2025-06-21 23:41:56,166] INFO in routes: testuser successfully logged out.
[2025-06-21 23:41:56,505] INFO in routes: testuser authenticated
[2025-06-21 23:41:56,508] INFO in routes: testuser accessed home page
[2025-06-21 23:41:56,510] INFO in routes: testuser accessed home page
[2025-06-21 23:41:56,849] INFO in routes: testuser authenticated
[2025-06-21 23:41:56,851] INFO in routes: testuser accessed home page
[2025-06-21 23:41:56,853] INFO in routes: testuser accessed home page
[2025-06-21 23:41:56,854] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-21 23:45:56,651] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: user_accounts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
                    ~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\models.py", line 122, in load_user
    return db.session.get(user_accounts, int(id))
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 1058, in get
    return self._proxied.get(
           ~~~~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<6 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3694, in get
    return self._get_impl(
           ~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<7 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3873, in _get_impl
    return db_load_fn(
        self,
    ...<5 lines>...
        bind_arguments=bind_arguments,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
    ~~~~~~~~~~~~~~~^
        q,
        ^^
    ...<2 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user_accounts
[SQL: SELECT user_accounts.user_account_id AS user_accounts_user_account_id, user_accounts.first_name AS user_accounts_first_name, user_accounts.last_name AS user_accounts_last_name, user_accounts.phone_number AS user_accounts_phone_number, user_accounts.account_created_date AS user_accounts_account_created_date, user_accounts.last_login AS user_accounts_last_login, user_accounts.is_deleted AS user_accounts_is_deleted, user_accounts.account_deleted_date AS user_accounts_account_deleted_date, user_accounts.is_admin AS user_accounts_is_admin 
FROM user_accounts 
WHERE user_accounts.user_account_id = ?]
[parameters: (2,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-21 23:49:34,122] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: user_accounts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
                    ~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
                                      ~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\app\models.py", line 122, in load_user
    return db.session.get(user_accounts, int(id))
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\scoping.py", line 1058, in get
    return self._proxied.get(
           ~~~~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<6 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3694, in get
    return self._get_impl(
           ~~~~~~~~~~~~~~^
        entity,
        ^^^^^^^
    ...<7 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 3873, in _get_impl
    return db_load_fn(
        self,
    ...<5 lines>...
        bind_arguments=bind_arguments,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
    ~~~~~~~~~~~~~~~^
        q,
        ^^
    ...<2 lines>...
        bind_arguments=bind_arguments,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        conn,
        ^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
        statement, params or {}, execution_options=execution_options
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1415, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rache\OneDrive\Desktop\SEA\fictional-umbrella\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: user_accounts
[SQL: SELECT user_accounts.user_account_id AS user_accounts_user_account_id, user_accounts.first_name AS user_accounts_first_name, user_accounts.last_name AS user_accounts_last_name, user_accounts.phone_number AS user_accounts_phone_number, user_accounts.account_created_date AS user_accounts_account_created_date, user_accounts.last_login AS user_accounts_last_login, user_accounts.is_deleted AS user_accounts_is_deleted, user_accounts.account_deleted_date AS user_accounts_account_deleted_date, user_accounts.is_admin AS user_accounts_is_admin 
FROM user_accounts 
WHERE user_accounts.user_account_id = ?]
[parameters: (2,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-21 23:56:37,893] INFO in routes: User1 accessed home page
[2025-06-21 23:56:47,827] INFO in routes: testuser authenticated
[2025-06-21 23:56:47,832] INFO in routes: testuser accessed home page
[2025-06-21 23:56:47,919] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-21 23:56:48,298] INFO in routes: testuser authenticated
[2025-06-21 23:56:48,300] INFO in routes: testuser accessed home page
[2025-06-21 23:56:48,302] INFO in routes: testuser successfully logged out.
[2025-06-21 23:56:48,654] INFO in routes: testuser authenticated
[2025-06-21 23:56:48,657] INFO in routes: testuser accessed home page
[2025-06-21 23:56:48,659] INFO in routes: testuser accessed home page
[2025-06-21 23:56:48,987] INFO in routes: testuser authenticated
[2025-06-21 23:56:48,989] INFO in routes: testuser accessed home page
[2025-06-21 23:56:48,991] INFO in routes: testuser accessed home page
[2025-06-21 23:56:48,992] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-21 23:57:00,363] ERROR in routes: Error retrieving login details for User1: (sqlite3.OperationalError) no such table: login_details
[SQL: SELECT login_details.login_id, login_details.user_account_id, login_details.username, login_details.email_address, login_details.password_hash 
FROM login_details 
WHERE login_details.username = ?]
[parameters: ('User1',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-21 23:57:06,063] ERROR in routes: Error retrieving login details for User1: (sqlite3.OperationalError) no such table: login_details
[SQL: SELECT login_details.login_id, login_details.user_account_id, login_details.username, login_details.email_address, login_details.password_hash 
FROM login_details 
WHERE login_details.username = ?]
[parameters: ('User1',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-21 23:57:56,913] ERROR in routes: Error retrieving login details for User1: (sqlite3.OperationalError) no such table: login_details
[SQL: SELECT login_details.login_id, login_details.user_account_id, login_details.username, login_details.email_address, login_details.password_hash 
FROM login_details 
WHERE login_details.username = ?]
[parameters: ('User1',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-22 00:08:32,697] ERROR in routes: Error retrieving login details for User1: (sqlite3.OperationalError) no such table: login_details
[SQL: SELECT login_details.login_id, login_details.user_account_id, login_details.username, login_details.email_address, login_details.password_hash 
FROM login_details 
WHERE login_details.username = ?]
[parameters: ('User1',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-22 00:10:09,270] INFO in routes: User1 authenticated
[2025-06-22 00:10:09,280] INFO in routes: User1 accessed home page
[2025-06-22 00:10:12,040] INFO in routes: User1 successfully logged out.
[2025-06-22 00:10:24,040] INFO in routes: testuser authenticated
[2025-06-22 00:10:24,046] INFO in routes: testuser accessed home page
[2025-06-22 00:10:24,133] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 00:10:24,472] INFO in routes: testuser authenticated
[2025-06-22 00:10:24,474] INFO in routes: testuser accessed home page
[2025-06-22 00:10:24,476] INFO in routes: testuser successfully logged out.
[2025-06-22 00:10:24,811] INFO in routes: testuser authenticated
[2025-06-22 00:10:24,814] INFO in routes: testuser accessed home page
[2025-06-22 00:10:24,816] INFO in routes: testuser accessed home page
[2025-06-22 00:10:25,144] INFO in routes: testuser authenticated
[2025-06-22 00:10:25,146] INFO in routes: testuser accessed home page
[2025-06-22 00:10:25,148] INFO in routes: testuser accessed home page
[2025-06-22 00:10:25,149] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 00:10:34,613] ERROR in routes: Error retrieving login details for User1: (sqlite3.OperationalError) no such table: login_details
[SQL: SELECT login_details.login_id, login_details.user_account_id, login_details.username, login_details.email_address, login_details.password_hash 
FROM login_details 
WHERE login_details.username = ?]
[parameters: ('User1',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-22 17:07:08,808] INFO in routes: testuser authenticated
[2025-06-22 17:07:08,815] INFO in routes: testuser accessed home page
[2025-06-22 17:07:09,026] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:07:09,465] INFO in routes: testuser authenticated
[2025-06-22 17:07:09,467] INFO in routes: testuser accessed home page
[2025-06-22 17:07:09,469] INFO in routes: testuser successfully logged out.
[2025-06-22 17:07:09,889] INFO in routes: testuser authenticated
[2025-06-22 17:07:09,891] INFO in routes: testuser accessed home page
[2025-06-22 17:07:09,893] INFO in routes: testuser accessed home page
[2025-06-22 17:07:10,314] INFO in routes: testuser authenticated
[2025-06-22 17:07:10,316] INFO in routes: testuser accessed home page
[2025-06-22 17:07:10,318] INFO in routes: testuser accessed home page
[2025-06-22 17:07:10,319] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:07:10,739] INFO in routes: testuser authenticated
[2025-06-22 17:07:10,741] INFO in routes: testuser accessed home page
[2025-06-22 17:08:28,161] INFO in routes: testuser authenticated
[2025-06-22 17:08:28,166] INFO in routes: testuser accessed home page
[2025-06-22 17:08:28,341] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:08:28,769] INFO in routes: testuser authenticated
[2025-06-22 17:08:28,771] INFO in routes: testuser accessed home page
[2025-06-22 17:08:28,773] INFO in routes: testuser successfully logged out.
[2025-06-22 17:08:29,210] INFO in routes: testuser authenticated
[2025-06-22 17:08:29,212] INFO in routes: testuser accessed home page
[2025-06-22 17:08:29,214] INFO in routes: testuser accessed home page
[2025-06-22 17:08:29,630] INFO in routes: testuser authenticated
[2025-06-22 17:08:29,632] INFO in routes: testuser accessed home page
[2025-06-22 17:08:29,635] INFO in routes: testuser accessed home page
[2025-06-22 17:08:29,635] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:08:30,054] INFO in routes: testuser authenticated
[2025-06-22 17:08:30,056] INFO in routes: testuser accessed home page
[2025-06-22 17:09:46,599] ERROR in routes: Error retrieving login details for User1: (sqlite3.OperationalError) no such table: login_details
[SQL: SELECT login_details.login_id, login_details.user_account_id, login_details.username, login_details.email_address, login_details.password_hash 
FROM login_details 
WHERE login_details.username = ?]
[parameters: ('User1',)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-22 17:10:23,869] ERROR in routes: Error creating new user: (sqlite3.OperationalError) no such table: user_accounts
[SQL: INSERT INTO user_accounts (first_name, last_name, phone_number, account_created_date, last_login, is_deleted, account_deleted_date, is_admin) VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, ?, ?) RETURNING user_account_id, account_created_date, last_login]
[parameters: ('User', '2', '07983764527', 0, None, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
[2025-06-22 17:17:24,479] INFO in routes: testuser authenticated
[2025-06-22 17:17:24,484] INFO in routes: testuser accessed home page
[2025-06-22 17:17:24,653] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:17:25,088] INFO in routes: testuser authenticated
[2025-06-22 17:17:25,090] INFO in routes: testuser accessed home page
[2025-06-22 17:17:25,091] INFO in routes: testuser successfully logged out.
[2025-06-22 17:17:25,520] INFO in routes: testuser authenticated
[2025-06-22 17:17:25,522] INFO in routes: testuser accessed home page
[2025-06-22 17:17:25,524] INFO in routes: testuser accessed home page
[2025-06-22 17:17:25,936] INFO in routes: testuser authenticated
[2025-06-22 17:17:25,938] INFO in routes: testuser accessed home page
[2025-06-22 17:17:25,941] INFO in routes: testuser accessed home page
[2025-06-22 17:17:25,941] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:17:26,375] INFO in routes: testuser authenticated
[2025-06-22 17:17:26,378] INFO in routes: testuser accessed home page
[2025-06-22 17:20:11,068] INFO in routes: testuser authenticated
[2025-06-22 17:20:11,073] INFO in routes: testuser accessed home page
[2025-06-22 17:20:11,256] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:20:11,706] INFO in routes: testuser authenticated
[2025-06-22 17:20:11,708] INFO in routes: testuser accessed home page
[2025-06-22 17:20:11,710] INFO in routes: testuser successfully logged out.
[2025-06-22 17:20:12,133] INFO in routes: testuser authenticated
[2025-06-22 17:20:12,135] INFO in routes: testuser accessed home page
[2025-06-22 17:20:12,136] INFO in routes: testuser accessed home page
[2025-06-22 17:20:12,543] INFO in routes: testuser authenticated
[2025-06-22 17:20:12,545] INFO in routes: testuser accessed home page
[2025-06-22 17:20:12,547] INFO in routes: testuser accessed home page
[2025-06-22 17:20:12,547] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:20:12,974] INFO in routes: testuser authenticated
[2025-06-22 17:20:12,976] INFO in routes: testuser accessed home page
[2025-06-22 17:20:44,128] INFO in routes: testuser authenticated
[2025-06-22 17:20:44,132] INFO in routes: testuser accessed home page
[2025-06-22 17:20:44,309] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:20:44,765] INFO in routes: testuser authenticated
[2025-06-22 17:20:44,767] INFO in routes: testuser accessed home page
[2025-06-22 17:20:44,769] INFO in routes: testuser successfully logged out.
[2025-06-22 17:20:45,188] INFO in routes: testuser authenticated
[2025-06-22 17:20:45,190] INFO in routes: testuser accessed home page
[2025-06-22 17:20:45,191] INFO in routes: testuser accessed home page
[2025-06-22 17:20:45,599] INFO in routes: testuser authenticated
[2025-06-22 17:20:45,601] INFO in routes: testuser accessed home page
[2025-06-22 17:20:45,603] INFO in routes: testuser accessed home page
[2025-06-22 17:20:45,603] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:20:46,023] INFO in routes: testuser authenticated
[2025-06-22 17:20:46,025] INFO in routes: testuser accessed home page
[2025-06-22 17:21:25,311] INFO in routes: testuser authenticated
[2025-06-22 17:21:25,316] INFO in routes: testuser accessed home page
[2025-06-22 17:21:25,529] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:21:26,041] INFO in routes: testuser authenticated
[2025-06-22 17:21:26,043] INFO in routes: testuser accessed home page
[2025-06-22 17:21:26,044] INFO in routes: testuser successfully logged out.
[2025-06-22 17:21:26,560] INFO in routes: testuser authenticated
[2025-06-22 17:21:26,562] INFO in routes: testuser accessed home page
[2025-06-22 17:21:26,564] INFO in routes: testuser accessed home page
[2025-06-22 17:21:27,018] INFO in routes: testuser authenticated
[2025-06-22 17:21:27,020] INFO in routes: testuser accessed home page
[2025-06-22 17:21:27,022] INFO in routes: testuser accessed home page
[2025-06-22 17:21:27,023] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:21:27,484] INFO in routes: testuser authenticated
[2025-06-22 17:21:27,486] INFO in routes: testuser accessed home page
[2025-06-22 17:21:27,867] INFO in routes: New user created: form.username
[2025-06-22 17:23:03,562] INFO in routes: testuser authenticated
[2025-06-22 17:23:03,567] INFO in routes: testuser accessed home page
[2025-06-22 17:23:03,745] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:23:04,173] INFO in routes: testuser authenticated
[2025-06-22 17:23:04,175] INFO in routes: testuser accessed home page
[2025-06-22 17:23:04,176] INFO in routes: testuser successfully logged out.
[2025-06-22 17:23:04,659] INFO in routes: testuser authenticated
[2025-06-22 17:23:04,661] INFO in routes: testuser accessed home page
[2025-06-22 17:23:04,663] INFO in routes: testuser accessed home page
[2025-06-22 17:23:05,083] INFO in routes: testuser authenticated
[2025-06-22 17:23:05,085] INFO in routes: testuser accessed home page
[2025-06-22 17:23:05,087] INFO in routes: testuser accessed home page
[2025-06-22 17:23:05,088] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:23:05,477] INFO in routes: testuser authenticated
[2025-06-22 17:23:05,479] INFO in routes: testuser accessed home page
[2025-06-22 17:23:05,819] INFO in routes: New user created: form.username
[2025-06-22 17:26:45,828] INFO in routes: testuser authenticated
[2025-06-22 17:26:45,833] INFO in routes: testuser accessed home page
[2025-06-22 17:26:45,998] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:26:46,432] INFO in routes: testuser authenticated
[2025-06-22 17:26:46,434] INFO in routes: testuser accessed home page
[2025-06-22 17:26:46,436] INFO in routes: testuser successfully logged out.
[2025-06-22 17:26:46,869] INFO in routes: testuser authenticated
[2025-06-22 17:26:46,871] INFO in routes: testuser accessed home page
[2025-06-22 17:26:46,873] INFO in routes: testuser accessed home page
[2025-06-22 17:26:47,288] INFO in routes: testuser authenticated
[2025-06-22 17:26:47,290] INFO in routes: testuser accessed home page
[2025-06-22 17:26:47,292] INFO in routes: testuser accessed home page
[2025-06-22 17:26:47,292] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:26:47,718] INFO in routes: testuser authenticated
[2025-06-22 17:26:47,720] INFO in routes: testuser accessed home page
[2025-06-22 17:26:48,061] INFO in routes: New user created: form.username
[2025-06-22 17:26:48,549] INFO in routes: New user created: form.username
[2025-06-22 17:28:17,699] INFO in routes: testuser authenticated
[2025-06-22 17:28:17,704] INFO in routes: testuser accessed home page
[2025-06-22 17:28:18,090] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:28:18,713] INFO in routes: testuser authenticated
[2025-06-22 17:28:18,716] INFO in routes: testuser accessed home page
[2025-06-22 17:28:18,717] INFO in routes: testuser successfully logged out.
[2025-06-22 17:28:19,394] INFO in routes: testuser authenticated
[2025-06-22 17:28:19,396] INFO in routes: testuser accessed home page
[2025-06-22 17:28:19,398] INFO in routes: testuser accessed home page
[2025-06-22 17:28:19,865] INFO in routes: testuser authenticated
[2025-06-22 17:28:19,867] INFO in routes: testuser accessed home page
[2025-06-22 17:28:19,869] INFO in routes: testuser accessed home page
[2025-06-22 17:28:19,869] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:28:20,285] INFO in routes: testuser authenticated
[2025-06-22 17:28:20,287] INFO in routes: testuser accessed home page
[2025-06-22 17:28:20,625] INFO in routes: New user created: form.username
[2025-06-22 17:28:20,954] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 17:42:42,988] INFO in routes: testuser authenticated
[2025-06-22 17:42:42,993] INFO in routes: testuser accessed home page
[2025-06-22 17:42:43,220] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:42:43,654] INFO in routes: testuser authenticated
[2025-06-22 17:42:43,656] INFO in routes: testuser accessed home page
[2025-06-22 17:42:43,658] INFO in routes: testuser successfully logged out.
[2025-06-22 17:42:44,071] INFO in routes: testuser authenticated
[2025-06-22 17:42:44,073] INFO in routes: testuser accessed home page
[2025-06-22 17:42:44,651] INFO in routes: testuser authenticated
[2025-06-22 17:42:44,653] INFO in routes: testuser accessed home page
[2025-06-22 17:42:44,655] INFO in routes: testuser accessed home page
[2025-06-22 17:42:45,066] INFO in routes: testuser authenticated
[2025-06-22 17:42:45,068] INFO in routes: testuser accessed home page
[2025-06-22 17:42:45,070] INFO in routes: testuser accessed home page
[2025-06-22 17:42:45,071] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:42:45,482] INFO in routes: testuser authenticated
[2025-06-22 17:42:45,484] INFO in routes: testuser accessed home page
[2025-06-22 17:42:45,825] INFO in routes: New user created: form.username
[2025-06-22 17:42:46,160] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 17:44:17,340] INFO in routes: testuser authenticated
[2025-06-22 17:44:17,344] INFO in routes: testuser accessed home page
[2025-06-22 17:44:17,519] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:44:17,968] INFO in routes: testuser authenticated
[2025-06-22 17:44:17,970] INFO in routes: testuser accessed home page
[2025-06-22 17:44:17,971] INFO in routes: testuser successfully logged out.
[2025-06-22 17:44:18,376] INFO in routes: testuser authenticated
[2025-06-22 17:44:18,378] INFO in routes: testuser accessed home page
[2025-06-22 17:44:18,953] INFO in routes: testuser authenticated
[2025-06-22 17:44:18,955] INFO in routes: testuser accessed home page
[2025-06-22 17:44:18,957] INFO in routes: testuser accessed home page
[2025-06-22 17:44:19,367] INFO in routes: testuser authenticated
[2025-06-22 17:44:19,369] INFO in routes: testuser accessed home page
[2025-06-22 17:44:19,371] INFO in routes: testuser accessed home page
[2025-06-22 17:44:19,371] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:44:19,790] INFO in routes: testuser authenticated
[2025-06-22 17:44:19,792] INFO in routes: testuser accessed home page
[2025-06-22 17:44:20,129] INFO in routes: New user created: form.username
[2025-06-22 17:44:20,483] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 17:45:04,801] INFO in routes: testuser authenticated
[2025-06-22 17:45:04,806] INFO in routes: testuser accessed home page
[2025-06-22 17:45:04,984] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:45:05,422] INFO in routes: testuser authenticated
[2025-06-22 17:45:05,424] INFO in routes: testuser accessed home page
[2025-06-22 17:45:05,425] INFO in routes: testuser successfully logged out.
[2025-06-22 17:45:05,838] INFO in routes: testuser authenticated
[2025-06-22 17:45:05,840] INFO in routes: testuser accessed home page
[2025-06-22 17:45:06,459] INFO in routes: testuser authenticated
[2025-06-22 17:45:06,461] INFO in routes: testuser accessed home page
[2025-06-22 17:45:06,463] INFO in routes: testuser accessed home page
[2025-06-22 17:45:06,872] INFO in routes: testuser authenticated
[2025-06-22 17:45:06,873] INFO in routes: testuser accessed home page
[2025-06-22 17:45:06,876] INFO in routes: testuser accessed home page
[2025-06-22 17:45:06,876] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:45:07,286] INFO in routes: testuser authenticated
[2025-06-22 17:45:07,288] INFO in routes: testuser accessed home page
[2025-06-22 17:45:07,650] INFO in routes: New user created: form.username
[2025-06-22 17:45:07,994] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 17:47:20,386] INFO in routes: testuser authenticated
[2025-06-22 17:47:20,390] INFO in routes: testuser accessed home page
[2025-06-22 17:47:20,560] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:47:20,997] INFO in routes: testuser authenticated
[2025-06-22 17:47:20,999] INFO in routes: testuser accessed home page
[2025-06-22 17:47:21,000] INFO in routes: testuser successfully logged out.
[2025-06-22 17:47:21,401] INFO in routes: testuser authenticated
[2025-06-22 17:47:21,403] INFO in routes: testuser accessed home page
[2025-06-22 17:47:21,985] INFO in routes: testuser authenticated
[2025-06-22 17:47:21,987] INFO in routes: testuser accessed home page
[2025-06-22 17:47:21,989] INFO in routes: testuser accessed home page
[2025-06-22 17:47:22,399] INFO in routes: testuser authenticated
[2025-06-22 17:47:22,401] INFO in routes: testuser accessed home page
[2025-06-22 17:47:22,403] INFO in routes: testuser accessed home page
[2025-06-22 17:47:22,404] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:47:22,813] INFO in routes: testuser authenticated
[2025-06-22 17:47:22,815] INFO in routes: testuser accessed home page
[2025-06-22 17:47:23,163] INFO in routes: New user created: form.username
[2025-06-22 17:47:23,493] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 17:48:14,808] INFO in routes: testuser authenticated
[2025-06-22 17:48:14,813] INFO in routes: testuser accessed home page
[2025-06-22 17:48:14,996] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:48:15,402] INFO in routes: testuser authenticated
[2025-06-22 17:48:15,406] INFO in routes: testuser accessed home page
[2025-06-22 17:48:15,408] INFO in routes: testuser successfully logged out.
[2025-06-22 17:48:15,816] INFO in routes: testuser authenticated
[2025-06-22 17:48:15,818] INFO in routes: testuser accessed home page
[2025-06-22 17:48:15,835] INFO in routes: New ticket created successfully 1
[2025-06-22 17:48:15,838] INFO in routes: testuser accessed home page
[2025-06-22 17:48:16,416] INFO in routes: testuser authenticated
[2025-06-22 17:48:16,418] INFO in routes: testuser accessed home page
[2025-06-22 17:48:16,420] INFO in routes: testuser accessed home page
[2025-06-22 17:48:16,852] INFO in routes: testuser authenticated
[2025-06-22 17:48:16,854] INFO in routes: testuser accessed home page
[2025-06-22 17:48:16,856] INFO in routes: testuser accessed home page
[2025-06-22 17:48:16,856] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:48:17,286] INFO in routes: testuser authenticated
[2025-06-22 17:48:17,288] INFO in routes: testuser accessed home page
[2025-06-22 17:48:17,632] INFO in routes: New user created: form.username
[2025-06-22 17:48:17,974] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 17:49:05,470] INFO in routes: testuser authenticated
[2025-06-22 17:49:05,474] INFO in routes: testuser accessed home page
[2025-06-22 17:49:05,648] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 17:49:06,081] INFO in routes: testuser authenticated
[2025-06-22 17:49:06,083] INFO in routes: testuser accessed home page
[2025-06-22 17:49:06,085] INFO in routes: testuser successfully logged out.
[2025-06-22 17:49:06,484] INFO in routes: testuser authenticated
[2025-06-22 17:49:06,487] INFO in routes: testuser accessed home page
[2025-06-22 17:49:06,505] INFO in routes: New ticket created successfully 1
[2025-06-22 17:49:06,508] INFO in routes: testuser accessed home page
[2025-06-22 17:49:06,939] INFO in routes: testuser authenticated
[2025-06-22 17:49:06,941] INFO in routes: testuser accessed home page
[2025-06-22 17:49:06,943] INFO in routes: testuser accessed home page
[2025-06-22 17:49:07,356] INFO in routes: testuser authenticated
[2025-06-22 17:49:07,358] INFO in routes: testuser accessed home page
[2025-06-22 17:49:07,360] INFO in routes: testuser accessed home page
[2025-06-22 17:49:07,360] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 17:49:07,781] INFO in routes: testuser authenticated
[2025-06-22 17:49:07,782] INFO in routes: testuser accessed home page
[2025-06-22 17:49:08,130] INFO in routes: New user created: form.username
[2025-06-22 17:49:08,458] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 20:57:08,569] INFO in routes: testuser authenticated
[2025-06-22 20:57:08,615] INFO in routes: testuser accessed home page
[2025-06-22 20:57:08,935] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 20:57:09,546] INFO in routes: testuser authenticated
[2025-06-22 20:57:09,548] INFO in routes: testuser accessed home page
[2025-06-22 20:57:09,550] INFO in routes: testuser successfully logged out.
[2025-06-22 20:57:10,152] INFO in routes: testuser authenticated
[2025-06-22 20:57:10,154] INFO in routes: testuser accessed home page
[2025-06-22 20:57:10,222] INFO in routes: New ticket created successfully 1
[2025-06-22 20:57:10,226] INFO in routes: testuser accessed home page
[2025-06-22 20:57:10,853] INFO in routes: testuser authenticated
[2025-06-22 20:57:10,855] INFO in routes: testuser accessed home page
[2025-06-22 20:57:11,885] INFO in routes: testuser authenticated
[2025-06-22 20:57:11,888] INFO in routes: testuser accessed home page
[2025-06-22 20:57:11,889] INFO in routes: testuser accessed home page
[2025-06-22 20:57:12,552] INFO in routes: testuser authenticated
[2025-06-22 20:57:12,554] INFO in routes: testuser accessed home page
[2025-06-22 20:57:12,557] INFO in routes: testuser accessed home page
[2025-06-22 20:57:12,557] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 20:57:13,050] INFO in routes: testuser authenticated
[2025-06-22 20:57:13,053] INFO in routes: testuser accessed home page
[2025-06-22 20:57:13,409] INFO in routes: New user created: form.username
[2025-06-22 20:57:13,754] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 20:57:46,650] INFO in routes: testuser authenticated
[2025-06-22 20:57:46,655] INFO in routes: testuser accessed home page
[2025-06-22 20:57:46,777] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 20:57:47,177] INFO in routes: testuser authenticated
[2025-06-22 20:57:47,179] INFO in routes: testuser accessed home page
[2025-06-22 20:57:47,180] INFO in routes: testuser successfully logged out.
[2025-06-22 20:57:47,598] INFO in routes: testuser authenticated
[2025-06-22 20:57:47,599] INFO in routes: testuser accessed home page
[2025-06-22 20:57:47,608] INFO in routes: New ticket created successfully 1
[2025-06-22 20:57:47,610] INFO in routes: testuser accessed home page
[2025-06-22 20:57:48,030] INFO in routes: testuser authenticated
[2025-06-22 20:57:48,032] INFO in routes: testuser accessed home page
[2025-06-22 20:57:48,449] INFO in routes: testuser authenticated
[2025-06-22 20:57:48,451] INFO in routes: testuser accessed home page
[2025-06-22 20:57:48,453] INFO in routes: testuser accessed home page
[2025-06-22 20:57:48,831] INFO in routes: testuser authenticated
[2025-06-22 20:57:48,833] INFO in routes: testuser accessed home page
[2025-06-22 20:57:48,836] INFO in routes: testuser accessed home page
[2025-06-22 20:57:48,836] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 20:57:49,330] INFO in routes: testuser authenticated
[2025-06-22 20:57:49,332] INFO in routes: testuser accessed home page
[2025-06-22 20:57:49,579] INFO in routes: New user created: form.username
[2025-06-22 20:57:49,743] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:00:38,885] INFO in routes: testuser authenticated
[2025-06-22 21:00:38,889] INFO in routes: testuser accessed home page
[2025-06-22 21:00:38,977] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 21:00:39,307] INFO in routes: testuser authenticated
[2025-06-22 21:00:39,309] INFO in routes: testuser accessed home page
[2025-06-22 21:00:39,311] INFO in routes: testuser successfully logged out.
[2025-06-22 21:00:39,670] INFO in routes: testuser authenticated
[2025-06-22 21:00:39,672] INFO in routes: testuser accessed home page
[2025-06-22 21:00:39,682] INFO in routes: New ticket created successfully 1
[2025-06-22 21:00:39,684] INFO in routes: testuser accessed home page
[2025-06-22 21:00:40,006] INFO in routes: testuser authenticated
[2025-06-22 21:00:40,008] INFO in routes: testuser accessed home page
[2025-06-22 21:00:40,339] INFO in routes: testuser authenticated
[2025-06-22 21:00:40,341] INFO in routes: testuser accessed home page
[2025-06-22 21:00:40,689] INFO in routes: testuser authenticated
[2025-06-22 21:00:40,691] INFO in routes: testuser accessed home page
[2025-06-22 21:00:40,693] INFO in routes: testuser accessed home page
[2025-06-22 21:00:41,014] INFO in routes: testuser authenticated
[2025-06-22 21:00:41,016] INFO in routes: testuser accessed home page
[2025-06-22 21:00:41,018] INFO in routes: testuser accessed home page
[2025-06-22 21:00:41,018] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 21:00:41,344] INFO in routes: testuser authenticated
[2025-06-22 21:00:41,347] INFO in routes: testuser accessed home page
[2025-06-22 21:00:41,597] INFO in routes: New user created: form.username
[2025-06-22 21:00:41,758] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:02:36,493] INFO in routes: testuser authenticated
[2025-06-22 21:02:36,498] INFO in routes: testuser accessed home page
[2025-06-22 21:02:36,587] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 21:02:36,914] INFO in routes: testuser authenticated
[2025-06-22 21:02:36,916] INFO in routes: testuser accessed home page
[2025-06-22 21:02:36,918] INFO in routes: testuser successfully logged out.
[2025-06-22 21:02:37,245] INFO in routes: testuser authenticated
[2025-06-22 21:02:37,247] INFO in routes: testuser accessed home page
[2025-06-22 21:02:37,257] INFO in routes: New ticket created successfully 1
[2025-06-22 21:02:37,260] INFO in routes: testuser accessed home page
[2025-06-22 21:02:37,589] INFO in routes: testuser authenticated
[2025-06-22 21:02:37,592] INFO in routes: testuser accessed home page
[2025-06-22 21:02:37,922] INFO in routes: testuser authenticated
[2025-06-22 21:02:37,924] INFO in routes: testuser accessed home page
[2025-06-22 21:02:37,927] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 21:02:38,265] INFO in routes: testuser authenticated
[2025-06-22 21:02:38,267] INFO in routes: testuser accessed home page
[2025-06-22 21:02:38,269] INFO in routes: testuser accessed home page
[2025-06-22 21:02:38,604] INFO in routes: testuser authenticated
[2025-06-22 21:02:38,606] INFO in routes: testuser accessed home page
[2025-06-22 21:02:38,608] INFO in routes: testuser accessed home page
[2025-06-22 21:02:38,608] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 21:02:38,929] INFO in routes: testuser authenticated
[2025-06-22 21:02:38,931] INFO in routes: testuser accessed home page
[2025-06-22 21:02:39,174] INFO in routes: New user created: form.username
[2025-06-22 21:02:39,342] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:31:52,676] INFO in routes: testuser authenticated
[2025-06-22 21:31:52,680] INFO in routes: testuser accessed home page
[2025-06-22 21:31:52,773] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 21:31:53,099] INFO in routes: testuser authenticated
[2025-06-22 21:31:53,101] INFO in routes: testuser accessed home page
[2025-06-22 21:31:53,102] INFO in routes: testuser successfully logged out.
[2025-06-22 21:31:53,441] INFO in routes: testuser authenticated
[2025-06-22 21:31:53,443] INFO in routes: testuser accessed home page
[2025-06-22 21:31:53,452] INFO in routes: New ticket created successfully 1
[2025-06-22 21:31:53,456] INFO in routes: testuser accessed home page
[2025-06-22 21:31:53,780] INFO in routes: testuser authenticated
[2025-06-22 21:31:53,782] INFO in routes: testuser accessed home page
[2025-06-22 21:31:54,113] INFO in routes: testuser authenticated
[2025-06-22 21:31:54,115] INFO in routes: testuser accessed home page
[2025-06-22 21:31:54,117] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 21:31:54,456] INFO in routes: testuser authenticated
[2025-06-22 21:31:54,458] INFO in routes: testuser accessed home page
[2025-06-22 21:31:54,460] INFO in routes: testuser accessed home page
[2025-06-22 21:31:54,785] INFO in routes: testuser authenticated
[2025-06-22 21:31:54,787] INFO in routes: testuser accessed home page
[2025-06-22 21:31:54,789] INFO in routes: testuser accessed home page
[2025-06-22 21:31:54,789] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 21:31:55,126] INFO in routes: testuser authenticated
[2025-06-22 21:31:55,129] INFO in routes: testuser accessed home page
[2025-06-22 21:31:55,371] INFO in routes: New user created: form.username
[2025-06-22 21:31:55,514] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:31:55,850] INFO in routes: testuser authenticated
[2025-06-22 21:31:55,852] INFO in routes: testuser accessed home page
[2025-06-22 21:31:55,854] INFO in routes: testuser view ticket 2
[2025-06-22 21:41:40,075] INFO in routes: testuser authenticated
[2025-06-22 21:41:40,080] INFO in routes: testuser accessed home page
[2025-06-22 21:41:40,162] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 21:41:40,495] INFO in routes: testuser authenticated
[2025-06-22 21:41:40,497] INFO in routes: testuser accessed home page
[2025-06-22 21:41:40,499] INFO in routes: testuser successfully logged out.
[2025-06-22 21:41:40,828] INFO in routes: testuser authenticated
[2025-06-22 21:41:40,830] INFO in routes: testuser accessed home page
[2025-06-22 21:41:40,840] INFO in routes: New ticket created successfully 1
[2025-06-22 21:41:40,843] INFO in routes: testuser accessed home page
[2025-06-22 21:41:41,170] INFO in routes: testuser authenticated
[2025-06-22 21:41:41,172] INFO in routes: testuser accessed home page
[2025-06-22 21:41:41,507] INFO in routes: testuser authenticated
[2025-06-22 21:41:41,509] INFO in routes: testuser accessed home page
[2025-06-22 21:41:41,511] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 21:41:41,849] INFO in routes: testuser authenticated
[2025-06-22 21:41:41,852] INFO in routes: testuser accessed home page
[2025-06-22 21:41:41,853] INFO in routes: testuser accessed home page
[2025-06-22 21:41:42,171] INFO in routes: testuser authenticated
[2025-06-22 21:41:42,173] INFO in routes: testuser accessed home page
[2025-06-22 21:41:42,175] INFO in routes: testuser accessed home page
[2025-06-22 21:41:42,176] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 21:41:42,502] INFO in routes: testuser authenticated
[2025-06-22 21:41:42,504] INFO in routes: testuser accessed home page
[2025-06-22 21:41:42,740] INFO in routes: New user created: form.username
[2025-06-22 21:41:42,872] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:41:43,202] INFO in routes: testuser authenticated
[2025-06-22 21:41:43,204] INFO in routes: testuser accessed home page
[2025-06-22 21:41:43,206] INFO in routes: testuser view ticket 2
[2025-06-22 21:41:43,560] INFO in routes: testuser authenticated
[2025-06-22 21:41:43,562] INFO in routes: testuser accessed home page
[2025-06-22 21:41:43,564] INFO in routes: testuser view ticket 2
[2025-06-22 21:42:42,607] INFO in routes: testuser authenticated
[2025-06-22 21:42:42,611] INFO in routes: testuser accessed home page
[2025-06-22 21:42:42,800] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 21:42:43,297] INFO in routes: testuser authenticated
[2025-06-22 21:42:43,299] INFO in routes: testuser accessed home page
[2025-06-22 21:42:43,300] INFO in routes: testuser successfully logged out.
[2025-06-22 21:42:43,690] INFO in routes: testuser authenticated
[2025-06-22 21:42:43,692] INFO in routes: testuser accessed home page
[2025-06-22 21:42:43,701] INFO in routes: New ticket created successfully 1
[2025-06-22 21:42:43,703] INFO in routes: testuser accessed home page
[2025-06-22 21:42:44,162] INFO in routes: testuser authenticated
[2025-06-22 21:42:44,164] INFO in routes: testuser accessed home page
[2025-06-22 21:42:44,585] INFO in routes: testuser authenticated
[2025-06-22 21:42:44,587] INFO in routes: testuser accessed home page
[2025-06-22 21:42:44,589] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 21:42:45,079] INFO in routes: testuser authenticated
[2025-06-22 21:42:45,081] INFO in routes: testuser accessed home page
[2025-06-22 21:42:45,082] INFO in routes: testuser accessed home page
[2025-06-22 21:42:45,587] INFO in routes: testuser authenticated
[2025-06-22 21:42:45,589] INFO in routes: testuser accessed home page
[2025-06-22 21:42:45,591] INFO in routes: testuser accessed home page
[2025-06-22 21:42:45,591] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 21:42:46,067] INFO in routes: testuser authenticated
[2025-06-22 21:42:46,069] INFO in routes: testuser accessed home page
[2025-06-22 21:42:46,660] INFO in routes: New user created: form.username
[2025-06-22 21:42:47,265] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:42:47,810] INFO in routes: testuser authenticated
[2025-06-22 21:42:47,812] INFO in routes: testuser accessed home page
[2025-06-22 21:42:47,814] INFO in routes: testuser view ticket 2
[2025-06-22 21:42:48,159] INFO in routes: testuser authenticated
[2025-06-22 21:42:48,161] INFO in routes: testuser accessed home page
[2025-06-22 21:42:48,163] INFO in routes: testuser view ticket 2
[2025-06-22 21:42:48,171] INFO in routes: Comment added successfully
[2025-06-22 21:42:48,172] INFO in routes: testuser view ticket 2
[2025-06-22 21:45:34,539] INFO in routes: testuser authenticated
[2025-06-22 21:45:34,544] INFO in routes: testuser accessed home page
[2025-06-22 21:45:34,625] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 21:45:34,968] INFO in routes: testuser authenticated
[2025-06-22 21:45:34,970] INFO in routes: testuser accessed home page
[2025-06-22 21:45:34,972] INFO in routes: testuser successfully logged out.
[2025-06-22 21:45:35,299] INFO in routes: testuser authenticated
[2025-06-22 21:45:35,301] INFO in routes: testuser accessed home page
[2025-06-22 21:45:35,310] INFO in routes: New ticket created successfully 1
[2025-06-22 21:45:35,312] INFO in routes: testuser accessed home page
[2025-06-22 21:45:35,637] INFO in routes: testuser authenticated
[2025-06-22 21:45:35,638] INFO in routes: testuser accessed home page
[2025-06-22 21:45:35,969] INFO in routes: testuser authenticated
[2025-06-22 21:45:35,970] INFO in routes: testuser accessed home page
[2025-06-22 21:45:35,973] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 21:45:36,315] INFO in routes: testuser authenticated
[2025-06-22 21:45:36,318] INFO in routes: testuser accessed home page
[2025-06-22 21:45:36,319] INFO in routes: testuser accessed home page
[2025-06-22 21:45:36,645] INFO in routes: testuser authenticated
[2025-06-22 21:45:36,647] INFO in routes: testuser accessed home page
[2025-06-22 21:45:36,649] INFO in routes: testuser accessed home page
[2025-06-22 21:45:36,649] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 21:45:36,974] INFO in routes: testuser authenticated
[2025-06-22 21:45:36,976] INFO in routes: testuser accessed home page
[2025-06-22 21:45:37,219] INFO in routes: New user created: form.username
[2025-06-22 21:45:37,373] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:45:37,703] INFO in routes: testuser authenticated
[2025-06-22 21:45:37,705] INFO in routes: testuser accessed home page
[2025-06-22 21:45:37,707] INFO in routes: testuser view ticket 2
[2025-06-22 21:45:38,042] INFO in routes: testuser authenticated
[2025-06-22 21:45:38,045] INFO in routes: testuser accessed home page
[2025-06-22 21:45:38,047] INFO in routes: testuser view ticket 2
[2025-06-22 21:45:38,053] INFO in routes: Comment added successfully
[2025-06-22 21:45:38,055] INFO in routes: testuser view ticket 2
[2025-06-22 21:45:38,389] INFO in routes: testuser authenticated
[2025-06-22 21:45:38,391] INFO in routes: testuser accessed home page
[2025-06-22 21:45:38,393] INFO in routes: testuser view ticket 2
[2025-06-22 21:45:38,394] ERROR in routes: Error adding comment: Simulated DB failure
[2025-06-22 21:45:38,395] INFO in routes: testuser view ticket 2
[2025-06-22 21:47:01,387] INFO in routes: testuser authenticated
[2025-06-22 21:47:01,391] INFO in routes: testuser accessed home page
[2025-06-22 21:47:01,487] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 21:47:01,829] INFO in routes: testuser authenticated
[2025-06-22 21:47:01,830] INFO in routes: testuser accessed home page
[2025-06-22 21:47:01,832] INFO in routes: testuser successfully logged out.
[2025-06-22 21:47:02,163] INFO in routes: testuser authenticated
[2025-06-22 21:47:02,165] INFO in routes: testuser accessed home page
[2025-06-22 21:47:02,175] INFO in routes: New ticket created successfully 1
[2025-06-22 21:47:02,178] INFO in routes: testuser accessed home page
[2025-06-22 21:47:02,508] INFO in routes: testuser authenticated
[2025-06-22 21:47:02,510] INFO in routes: testuser accessed home page
[2025-06-22 21:47:02,839] INFO in routes: testuser authenticated
[2025-06-22 21:47:02,841] INFO in routes: testuser accessed home page
[2025-06-22 21:47:02,844] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 21:47:03,184] INFO in routes: testuser authenticated
[2025-06-22 21:47:03,186] INFO in routes: testuser accessed home page
[2025-06-22 21:47:03,187] INFO in routes: testuser accessed home page
[2025-06-22 21:47:03,506] INFO in routes: testuser authenticated
[2025-06-22 21:47:03,508] INFO in routes: testuser accessed home page
[2025-06-22 21:47:03,510] INFO in routes: testuser accessed home page
[2025-06-22 21:47:03,510] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 21:47:03,830] INFO in routes: testuser authenticated
[2025-06-22 21:47:03,832] INFO in routes: testuser accessed home page
[2025-06-22 21:47:04,072] INFO in routes: New user created: form.username
[2025-06-22 21:47:04,224] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:47:04,554] INFO in routes: testuser authenticated
[2025-06-22 21:47:04,556] INFO in routes: testuser accessed home page
[2025-06-22 21:47:04,557] INFO in routes: testuser view ticket 2
[2025-06-22 21:47:04,897] INFO in routes: testuser authenticated
[2025-06-22 21:47:04,899] INFO in routes: testuser accessed home page
[2025-06-22 21:47:04,902] INFO in routes: testuser view ticket 2
[2025-06-22 21:47:04,908] INFO in routes: Comment added successfully
[2025-06-22 21:47:04,911] INFO in routes: testuser view ticket 2
[2025-06-22 21:47:05,244] INFO in routes: testuser authenticated
[2025-06-22 21:47:05,246] INFO in routes: testuser accessed home page
[2025-06-22 21:47:05,247] INFO in routes: testuser view ticket 2
[2025-06-22 21:47:05,578] INFO in routes: testuser authenticated
[2025-06-22 21:47:05,580] INFO in routes: testuser accessed home page
[2025-06-22 21:47:05,582] INFO in routes: testuser view ticket 2
[2025-06-22 21:47:05,583] ERROR in routes: Error adding comment: Simulated DB failure
[2025-06-22 21:47:05,584] INFO in routes: testuser view ticket 2
[2025-06-22 21:56:53,904] INFO in routes: testuser authenticated
[2025-06-22 21:56:53,909] INFO in routes: testuser accessed home page
[2025-06-22 21:56:53,993] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 21:56:54,323] INFO in routes: testuser authenticated
[2025-06-22 21:56:54,326] INFO in routes: testuser accessed home page
[2025-06-22 21:56:54,327] INFO in routes: testuser successfully logged out.
[2025-06-22 21:56:54,654] INFO in routes: testuser authenticated
[2025-06-22 21:56:54,656] INFO in routes: testuser accessed home page
[2025-06-22 21:56:54,666] INFO in routes: New ticket created successfully 1
[2025-06-22 21:56:54,670] INFO in routes: testuser accessed home page
[2025-06-22 21:56:54,992] INFO in routes: testuser authenticated
[2025-06-22 21:56:54,994] INFO in routes: testuser accessed home page
[2025-06-22 21:56:55,324] INFO in routes: testuser authenticated
[2025-06-22 21:56:55,326] INFO in routes: testuser accessed home page
[2025-06-22 21:56:55,329] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 21:56:55,664] INFO in routes: testuser authenticated
[2025-06-22 21:56:55,666] INFO in routes: testuser accessed home page
[2025-06-22 21:56:55,668] INFO in routes: testuser accessed home page
[2025-06-22 21:56:55,993] INFO in routes: testuser authenticated
[2025-06-22 21:56:55,994] INFO in routes: testuser accessed home page
[2025-06-22 21:56:55,996] INFO in routes: testuser accessed home page
[2025-06-22 21:56:55,997] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 21:56:56,319] INFO in routes: testuser authenticated
[2025-06-22 21:56:56,321] INFO in routes: testuser accessed home page
[2025-06-22 21:56:56,576] INFO in routes: New user created: form.username
[2025-06-22 21:56:56,733] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:56:57,061] INFO in routes: testuser authenticated
[2025-06-22 21:56:57,063] INFO in routes: testuser accessed home page
[2025-06-22 21:56:57,065] INFO in routes: testuser view ticket 2
[2025-06-22 21:56:57,406] INFO in routes: testuser authenticated
[2025-06-22 21:56:57,408] INFO in routes: testuser accessed home page
[2025-06-22 21:56:57,410] INFO in routes: testuser view ticket 2
[2025-06-22 21:56:57,416] INFO in routes: Comment added successfully
[2025-06-22 21:56:57,419] INFO in routes: testuser view ticket 2
[2025-06-22 21:56:57,757] INFO in routes: testuser authenticated
[2025-06-22 21:56:57,759] INFO in routes: testuser accessed home page
[2025-06-22 21:56:57,761] INFO in routes: testuser view ticket 2
[2025-06-22 21:56:58,090] INFO in routes: testuser authenticated
[2025-06-22 21:56:58,092] INFO in routes: testuser accessed home page
[2025-06-22 21:56:58,094] INFO in routes: testuser view ticket 2
[2025-06-22 21:56:58,095] ERROR in routes: Error adding comment: Simulated DB failure
[2025-06-22 21:56:58,096] INFO in routes: testuser view ticket 2
[2025-06-22 21:56:58,557] INFO in routes: testadmin authenticated
[2025-06-22 21:56:58,559] INFO in routes: testadmin accessed home page
[2025-06-22 21:56:58,578] INFO in routes: testadmin view ticket 2
[2025-06-22 21:56:58,593] INFO in routes: Comment added successfully
[2025-06-22 21:56:58,594] INFO in routes: testadmin view ticket 2
[2025-06-22 21:57:16,010] INFO in routes: testuser authenticated
[2025-06-22 21:57:16,015] INFO in routes: testuser accessed home page
[2025-06-22 21:57:16,102] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 21:57:16,428] INFO in routes: testuser authenticated
[2025-06-22 21:57:16,430] INFO in routes: testuser accessed home page
[2025-06-22 21:57:16,431] INFO in routes: testuser successfully logged out.
[2025-06-22 21:57:16,764] INFO in routes: testuser authenticated
[2025-06-22 21:57:16,766] INFO in routes: testuser accessed home page
[2025-06-22 21:57:16,776] INFO in routes: New ticket created successfully 1
[2025-06-22 21:57:16,778] INFO in routes: testuser accessed home page
[2025-06-22 21:57:17,093] INFO in routes: testuser authenticated
[2025-06-22 21:57:17,095] INFO in routes: testuser accessed home page
[2025-06-22 21:57:17,426] INFO in routes: testuser authenticated
[2025-06-22 21:57:17,428] INFO in routes: testuser accessed home page
[2025-06-22 21:57:17,430] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 21:57:17,761] INFO in routes: testuser authenticated
[2025-06-22 21:57:17,764] INFO in routes: testuser accessed home page
[2025-06-22 21:57:17,766] INFO in routes: testuser accessed home page
[2025-06-22 21:57:18,093] INFO in routes: testuser authenticated
[2025-06-22 21:57:18,095] INFO in routes: testuser accessed home page
[2025-06-22 21:57:18,097] INFO in routes: testuser accessed home page
[2025-06-22 21:57:18,097] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 21:57:18,427] INFO in routes: testuser authenticated
[2025-06-22 21:57:18,428] INFO in routes: testuser accessed home page
[2025-06-22 21:57:18,670] INFO in routes: New user created: form.username
[2025-06-22 21:57:18,844] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:57:19,181] INFO in routes: testuser authenticated
[2025-06-22 21:57:19,183] INFO in routes: testuser accessed home page
[2025-06-22 21:57:19,185] INFO in routes: testuser view ticket 2
[2025-06-22 21:57:19,522] INFO in routes: testuser authenticated
[2025-06-22 21:57:19,524] INFO in routes: testuser accessed home page
[2025-06-22 21:57:19,526] INFO in routes: testuser view ticket 2
[2025-06-22 21:57:19,533] INFO in routes: Comment added successfully
[2025-06-22 21:57:19,535] INFO in routes: testuser view ticket 2
[2025-06-22 21:57:19,861] INFO in routes: testuser authenticated
[2025-06-22 21:57:19,863] INFO in routes: testuser accessed home page
[2025-06-22 21:57:19,865] INFO in routes: testuser view ticket 2
[2025-06-22 21:57:20,196] INFO in routes: testuser authenticated
[2025-06-22 21:57:20,198] INFO in routes: testuser accessed home page
[2025-06-22 21:57:20,200] INFO in routes: testuser view ticket 2
[2025-06-22 21:57:20,201] ERROR in routes: Error adding comment: Simulated DB failure
[2025-06-22 21:57:20,203] INFO in routes: testuser view ticket 2
[2025-06-22 21:57:20,663] INFO in routes: testadmin authenticated
[2025-06-22 21:57:20,665] INFO in routes: testadmin accessed home page
[2025-06-22 21:57:20,670] INFO in routes: testadmin view ticket 2
[2025-06-22 21:57:20,685] INFO in routes: Comment added successfully
[2025-06-22 21:57:20,688] INFO in routes: testadmin view ticket 2
[2025-06-22 21:59:10,094] INFO in routes: testuser authenticated
[2025-06-22 21:59:10,099] INFO in routes: testuser accessed home page
[2025-06-22 21:59:10,183] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 21:59:10,510] INFO in routes: testuser authenticated
[2025-06-22 21:59:10,512] INFO in routes: testuser accessed home page
[2025-06-22 21:59:10,514] INFO in routes: testuser successfully logged out.
[2025-06-22 21:59:10,839] INFO in routes: testuser authenticated
[2025-06-22 21:59:10,842] INFO in routes: testuser accessed home page
[2025-06-22 21:59:10,851] INFO in routes: New ticket created successfully 1
[2025-06-22 21:59:10,855] INFO in routes: testuser accessed home page
[2025-06-22 21:59:11,183] INFO in routes: testuser authenticated
[2025-06-22 21:59:11,185] INFO in routes: testuser accessed home page
[2025-06-22 21:59:11,532] INFO in routes: testuser authenticated
[2025-06-22 21:59:11,534] INFO in routes: testuser accessed home page
[2025-06-22 21:59:11,536] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 21:59:11,865] INFO in routes: testuser authenticated
[2025-06-22 21:59:11,868] INFO in routes: testuser accessed home page
[2025-06-22 21:59:11,869] INFO in routes: testuser accessed home page
[2025-06-22 21:59:12,191] INFO in routes: testuser authenticated
[2025-06-22 21:59:12,193] INFO in routes: testuser accessed home page
[2025-06-22 21:59:12,195] INFO in routes: testuser accessed home page
[2025-06-22 21:59:12,196] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 21:59:12,525] INFO in routes: testuser authenticated
[2025-06-22 21:59:12,528] INFO in routes: testuser accessed home page
[2025-06-22 21:59:12,763] INFO in routes: New user created: form.username
[2025-06-22 21:59:12,916] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 21:59:13,250] INFO in routes: testuser authenticated
[2025-06-22 21:59:13,252] INFO in routes: testuser accessed home page
[2025-06-22 21:59:13,254] INFO in routes: testuser view ticket 2
[2025-06-22 21:59:13,597] INFO in routes: testuser authenticated
[2025-06-22 21:59:13,599] INFO in routes: testuser accessed home page
[2025-06-22 21:59:13,601] INFO in routes: testuser view ticket 2
[2025-06-22 21:59:13,608] INFO in routes: Comment added successfully
[2025-06-22 21:59:13,610] INFO in routes: testuser view ticket 2
[2025-06-22 21:59:13,940] INFO in routes: testuser authenticated
[2025-06-22 21:59:13,942] INFO in routes: testuser accessed home page
[2025-06-22 21:59:13,944] INFO in routes: testuser view ticket 2
[2025-06-22 21:59:14,284] INFO in routes: testuser authenticated
[2025-06-22 21:59:14,286] INFO in routes: testuser accessed home page
[2025-06-22 21:59:14,288] INFO in routes: testuser view ticket 2
[2025-06-22 21:59:14,289] ERROR in routes: Error adding comment: Simulated DB failure
[2025-06-22 21:59:14,290] INFO in routes: testuser view ticket 2
[2025-06-22 21:59:14,741] INFO in routes: testadmin authenticated
[2025-06-22 21:59:14,743] INFO in routes: testadmin accessed home page
[2025-06-22 21:59:14,748] INFO in routes: testadmin view ticket 2
[2025-06-22 21:59:14,761] INFO in routes: Comment added successfully
[2025-06-22 21:59:14,764] INFO in routes: testadmin view ticket 2
[2025-06-22 22:00:42,221] INFO in routes: testuser authenticated
[2025-06-22 22:00:42,226] INFO in routes: testuser accessed home page
[2025-06-22 22:00:42,356] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 22:00:42,735] INFO in routes: testuser authenticated
[2025-06-22 22:00:42,737] INFO in routes: testuser accessed home page
[2025-06-22 22:00:42,739] INFO in routes: testuser successfully logged out.
[2025-06-22 22:00:43,094] INFO in routes: testuser authenticated
[2025-06-22 22:00:43,096] INFO in routes: testuser accessed home page
[2025-06-22 22:00:43,106] INFO in routes: New ticket created successfully 1
[2025-06-22 22:00:43,108] INFO in routes: testuser accessed home page
[2025-06-22 22:00:43,556] INFO in routes: testuser authenticated
[2025-06-22 22:00:43,558] INFO in routes: testuser accessed home page
[2025-06-22 22:00:43,883] INFO in routes: testuser authenticated
[2025-06-22 22:00:43,885] INFO in routes: testuser accessed home page
[2025-06-22 22:00:43,888] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 22:00:44,226] INFO in routes: testuser authenticated
[2025-06-22 22:00:44,228] INFO in routes: testuser accessed home page
[2025-06-22 22:00:44,230] INFO in routes: testuser accessed home page
[2025-06-22 22:00:44,618] INFO in routes: testuser authenticated
[2025-06-22 22:00:44,620] INFO in routes: testuser accessed home page
[2025-06-22 22:00:44,622] INFO in routes: testuser accessed home page
[2025-06-22 22:00:44,622] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 22:00:44,940] INFO in routes: testuser authenticated
[2025-06-22 22:00:44,942] INFO in routes: testuser accessed home page
[2025-06-22 22:00:45,213] INFO in routes: New user created: form.username
[2025-06-22 22:00:45,348] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 22:00:45,686] INFO in routes: testuser authenticated
[2025-06-22 22:00:45,688] INFO in routes: testuser accessed home page
[2025-06-22 22:00:45,690] INFO in routes: testuser view ticket 2
[2025-06-22 22:00:46,048] INFO in routes: testuser authenticated
[2025-06-22 22:00:46,050] INFO in routes: testuser accessed home page
[2025-06-22 22:00:46,052] INFO in routes: testuser view ticket 2
[2025-06-22 22:00:46,085] INFO in routes: Comment added successfully
[2025-06-22 22:00:46,087] INFO in routes: testuser view ticket 2
[2025-06-22 22:00:46,417] INFO in routes: testuser authenticated
[2025-06-22 22:00:46,419] INFO in routes: testuser accessed home page
[2025-06-22 22:00:46,421] INFO in routes: testuser view ticket 2
[2025-06-22 22:00:46,809] INFO in routes: testuser authenticated
[2025-06-22 22:00:46,811] INFO in routes: testuser accessed home page
[2025-06-22 22:00:46,813] INFO in routes: testuser view ticket 2
[2025-06-22 22:00:46,814] ERROR in routes: Error adding comment: Simulated DB failure
[2025-06-22 22:00:46,816] INFO in routes: testuser view ticket 2
[2025-06-22 22:00:47,274] INFO in routes: testadmin authenticated
[2025-06-22 22:00:47,276] INFO in routes: testadmin accessed home page
[2025-06-22 22:00:47,281] INFO in routes: testadmin view ticket 2
[2025-06-22 22:00:47,296] INFO in routes: Comment added successfully
[2025-06-22 22:00:47,299] INFO in routes: testadmin view ticket 2
[2025-06-22 22:01:05,140] INFO in routes: testuser authenticated
[2025-06-22 22:01:05,145] INFO in routes: testuser accessed home page
[2025-06-22 22:01:05,232] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 22:01:05,560] INFO in routes: testuser authenticated
[2025-06-22 22:01:05,562] INFO in routes: testuser accessed home page
[2025-06-22 22:01:05,565] INFO in routes: testuser successfully logged out.
[2025-06-22 22:01:05,921] INFO in routes: testuser authenticated
[2025-06-22 22:01:05,924] INFO in routes: testuser accessed home page
[2025-06-22 22:01:05,935] INFO in routes: New ticket created successfully 1
[2025-06-22 22:01:05,937] INFO in routes: testuser accessed home page
[2025-06-22 22:01:06,269] INFO in routes: testuser authenticated
[2025-06-22 22:01:06,271] INFO in routes: testuser accessed home page
[2025-06-22 22:01:06,618] INFO in routes: testuser authenticated
[2025-06-22 22:01:06,620] INFO in routes: testuser accessed home page
[2025-06-22 22:01:06,623] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 22:01:06,970] INFO in routes: testuser authenticated
[2025-06-22 22:01:06,972] INFO in routes: testuser accessed home page
[2025-06-22 22:01:06,974] INFO in routes: testuser accessed home page
[2025-06-22 22:01:07,298] INFO in routes: testuser authenticated
[2025-06-22 22:01:07,300] INFO in routes: testuser accessed home page
[2025-06-22 22:01:07,302] INFO in routes: testuser accessed home page
[2025-06-22 22:01:07,302] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 22:01:07,622] INFO in routes: testuser authenticated
[2025-06-22 22:01:07,624] INFO in routes: testuser accessed home page
[2025-06-22 22:01:07,869] INFO in routes: New user created: form.username
[2025-06-22 22:01:08,010] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 22:01:08,345] INFO in routes: testuser authenticated
[2025-06-22 22:01:08,347] INFO in routes: testuser accessed home page
[2025-06-22 22:01:08,349] INFO in routes: testuser view ticket 2
[2025-06-22 22:01:08,689] INFO in routes: testuser authenticated
[2025-06-22 22:01:08,691] INFO in routes: testuser accessed home page
[2025-06-22 22:01:08,694] INFO in routes: testuser view ticket 2
[2025-06-22 22:01:08,703] INFO in routes: Comment added successfully
[2025-06-22 22:01:08,705] INFO in routes: testuser view ticket 2
[2025-06-22 22:01:09,038] INFO in routes: testuser authenticated
[2025-06-22 22:01:09,040] INFO in routes: testuser accessed home page
[2025-06-22 22:01:09,041] INFO in routes: testuser view ticket 2
[2025-06-22 22:01:09,371] INFO in routes: testuser authenticated
[2025-06-22 22:01:09,373] INFO in routes: testuser accessed home page
[2025-06-22 22:01:09,375] INFO in routes: testuser view ticket 2
[2025-06-22 22:01:09,376] ERROR in routes: Error adding comment: Simulated DB failure
[2025-06-22 22:01:09,378] INFO in routes: testuser view ticket 2
[2025-06-22 22:01:09,846] INFO in routes: testadmin authenticated
[2025-06-22 22:01:09,848] INFO in routes: testadmin accessed home page
[2025-06-22 22:01:09,853] INFO in routes: testadmin view ticket 2
[2025-06-22 22:01:09,867] INFO in routes: Comment added successfully
[2025-06-22 22:01:09,869] INFO in routes: testadmin view ticket 2
[2025-06-22 22:08:15,654] INFO in routes: testuser authenticated
[2025-06-22 22:08:15,659] INFO in routes: testuser accessed home page
[2025-06-22 22:08:15,758] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 22:08:16,094] INFO in routes: testuser authenticated
[2025-06-22 22:08:16,096] INFO in routes: testuser accessed home page
[2025-06-22 22:08:16,098] INFO in routes: testuser successfully logged out.
[2025-06-22 22:08:16,424] INFO in routes: testuser authenticated
[2025-06-22 22:08:16,426] INFO in routes: testuser accessed home page
[2025-06-22 22:08:16,436] INFO in routes: New ticket created successfully 1
[2025-06-22 22:08:16,438] INFO in routes: testuser accessed home page
[2025-06-22 22:08:16,768] INFO in routes: testuser authenticated
[2025-06-22 22:08:16,770] INFO in routes: testuser accessed home page
[2025-06-22 22:08:17,099] INFO in routes: testuser authenticated
[2025-06-22 22:08:17,101] INFO in routes: testuser accessed home page
[2025-06-22 22:08:17,103] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 22:08:17,446] INFO in routes: testuser authenticated
[2025-06-22 22:08:17,448] INFO in routes: testuser accessed home page
[2025-06-22 22:08:17,450] INFO in routes: testuser accessed home page
[2025-06-22 22:08:17,770] INFO in routes: testuser authenticated
[2025-06-22 22:08:17,772] INFO in routes: testuser accessed home page
[2025-06-22 22:08:17,774] INFO in routes: testuser accessed home page
[2025-06-22 22:08:17,775] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 22:08:18,096] INFO in routes: testuser authenticated
[2025-06-22 22:08:18,098] INFO in routes: testuser accessed home page
[2025-06-22 22:08:18,380] INFO in routes: New user created: form.username
[2025-06-22 22:08:18,547] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 22:08:18,872] INFO in routes: testuser authenticated
[2025-06-22 22:08:18,874] INFO in routes: testuser accessed home page
[2025-06-22 22:08:18,876] INFO in routes: testuser view ticket 2
[2025-06-22 22:08:19,209] INFO in routes: testuser authenticated
[2025-06-22 22:08:19,211] INFO in routes: testuser accessed home page
[2025-06-22 22:08:19,213] INFO in routes: testuser view ticket 2
[2025-06-22 22:08:19,219] INFO in routes: Comment added successfully
[2025-06-22 22:08:19,220] INFO in routes: testuser view ticket 2
[2025-06-22 22:08:19,552] INFO in routes: testuser authenticated
[2025-06-22 22:08:19,554] INFO in routes: testuser accessed home page
[2025-06-22 22:08:19,555] INFO in routes: testuser view ticket 2
[2025-06-22 22:08:19,893] INFO in routes: testuser authenticated
[2025-06-22 22:08:19,896] INFO in routes: testuser accessed home page
[2025-06-22 22:08:19,897] INFO in routes: testuser view ticket 2
[2025-06-22 22:08:19,898] ERROR in routes: Error adding comment: Simulated DB failure
[2025-06-22 22:08:19,900] INFO in routes: testuser view ticket 2
[2025-06-22 22:08:20,363] INFO in routes: testadmin authenticated
[2025-06-22 22:08:20,365] INFO in routes: testadmin accessed home page
[2025-06-22 22:08:20,371] INFO in routes: testadmin view ticket 2
[2025-06-22 22:08:20,386] INFO in routes: Comment added successfully
[2025-06-22 22:08:20,388] INFO in routes: testadmin view ticket 2
[2025-06-22 22:08:20,599] WARNING in routes: Failed login attempt: testadmin. Validation errors: {}
[2025-06-22 22:09:40,990] INFO in routes: testuser authenticated
[2025-06-22 22:09:40,995] INFO in routes: testuser accessed home page
[2025-06-22 22:09:41,156] WARNING in routes: Failed login attempt: wronguser. Validation errors: {}
[2025-06-22 22:09:41,535] INFO in routes: testuser authenticated
[2025-06-22 22:09:41,537] INFO in routes: testuser accessed home page
[2025-06-22 22:09:41,538] INFO in routes: testuser successfully logged out.
[2025-06-22 22:09:41,887] INFO in routes: testuser authenticated
[2025-06-22 22:09:41,889] INFO in routes: testuser accessed home page
[2025-06-22 22:09:41,900] INFO in routes: New ticket created successfully 1
[2025-06-22 22:09:41,902] INFO in routes: testuser accessed home page
[2025-06-22 22:09:42,290] INFO in routes: testuser authenticated
[2025-06-22 22:09:42,292] INFO in routes: testuser accessed home page
[2025-06-22 22:09:42,727] INFO in routes: testuser authenticated
[2025-06-22 22:09:42,729] INFO in routes: testuser accessed home page
[2025-06-22 22:09:42,731] ERROR in routes: Error creating new ticket: Simulated DB failure
[2025-06-22 22:09:43,069] INFO in routes: testuser authenticated
[2025-06-22 22:09:43,071] INFO in routes: testuser accessed home page
[2025-06-22 22:09:43,073] INFO in routes: testuser accessed home page
[2025-06-22 22:09:43,407] INFO in routes: testuser authenticated
[2025-06-22 22:09:43,409] INFO in routes: testuser accessed home page
[2025-06-22 22:09:43,411] INFO in routes: testuser accessed home page
[2025-06-22 22:09:43,411] ERROR in routes: Error retrieving ticket summary stats: Simulated DB failure
[2025-06-22 22:09:43,738] INFO in routes: testuser authenticated
[2025-06-22 22:09:43,740] INFO in routes: testuser accessed home page
[2025-06-22 22:09:43,982] INFO in routes: New user created: form.username
[2025-06-22 22:09:44,161] ERROR in routes: Error creating new user: Simulated DB failure
[2025-06-22 22:09:44,495] INFO in routes: testuser authenticated
[2025-06-22 22:09:44,497] INFO in routes: testuser accessed home page
[2025-06-22 22:09:44,499] INFO in routes: testuser view ticket 2
[2025-06-22 22:09:44,836] INFO in routes: testuser authenticated
[2025-06-22 22:09:44,838] INFO in routes: testuser accessed home page
[2025-06-22 22:09:44,840] INFO in routes: testuser view ticket 2
[2025-06-22 22:09:44,848] INFO in routes: Comment added successfully
[2025-06-22 22:09:44,849] INFO in routes: testuser view ticket 2
[2025-06-22 22:09:45,183] INFO in routes: testuser authenticated
[2025-06-22 22:09:45,185] INFO in routes: testuser accessed home page
[2025-06-22 22:09:45,187] INFO in routes: testuser view ticket 2
[2025-06-22 22:09:45,524] INFO in routes: testuser authenticated
[2025-06-22 22:09:45,526] INFO in routes: testuser accessed home page
[2025-06-22 22:09:45,528] INFO in routes: testuser view ticket 2
[2025-06-22 22:09:45,529] ERROR in routes: Error adding comment: Simulated DB failure
[2025-06-22 22:09:45,530] INFO in routes: testuser view ticket 2
[2025-06-22 22:09:45,990] INFO in routes: testadmin authenticated
[2025-06-22 22:09:45,992] INFO in routes: testadmin accessed home page
[2025-06-22 22:09:45,997] INFO in routes: testadmin view ticket 2
[2025-06-22 22:09:46,012] INFO in routes: Comment added successfully
[2025-06-22 22:09:46,013] INFO in routes: testadmin view ticket 2
[2025-06-22 22:09:46,354] INFO in routes: testuser authenticated
[2025-06-22 22:09:46,357] INFO in routes: testuser accessed home page
[2025-06-22 22:09:46,359] INFO in routes: testuser view ticket 2
